#!/bin/sh
###################################################################
# /etc/NetworkManager/dispatcher.d/52-start-pws-client
# This file starts/stops pws_client on network connection/disconnection
# If you use NetworkManager dispatcher
# https://wiki.archlinux.org/index.php/NetworkManager#Network_services_with_NetworkManager_dispatcher
###################################################################
echo "Executing PWS client dispatcher script"

if [ "$2" == 'down' ]; then
    echo "connection down"
    if ! ping google.fr -c 1 -W 1 && (systemctl status pws_client | grep "Active: active" > /dev/null); then
      echo "stopping pws_client"
      systemctl stop pws_client
    fi
elif [ "$2" == 'up' ]; then
    echo "connection up"
    if ! systemctl status pws_client |grep "Active: active" > /dev/null; then
      echo "restarting pws_client"
      systemctl restart pws_client
    fi

else
    echo "nothing to do for event $2"
fi
exit 0
